import React from "react";

const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: "2rem",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    minHeight: "calc(100vh - 60px)",
  },
  title: {
    fontSize: "2.5rem",
    marginBottom: "1rem",
    color: "#ff6b35",
    textShadow: "2px 2px 4px rgba(0,0,0,0.1)",
  },
  tabs: {
    display: "flex",
    gap: "0.5rem",
    marginBottom: "1.5rem",
    borderBottom: "2px solid #f7931e",
  },
  tab: {
    backgroundColor: "transparent",
    border: "2px solid #f7931e",
    borderBottom: "none",
    borderRadius: "8px 8px 0 0",
    padding: "0.6rem 1.5rem",
    cursor: "pointer",
    fontSize: "1rem",
    fontWeight: "600",
    color: "#f7931e",
    transition: "all 0.2s ease",
    marginBottom: "-2px",
  },
  tabActive: {
    backgroundColor: "#f7931e",
    color: "#fff",
  },
  error: {
    backgroundColor: "#ffebee",
    border: "2px solid #f44336",
    color: "#d32f2f",
    padding: "1rem",
    borderRadius: "8px",
    marginBottom: "1rem",
  },
  modal: {
    position: "fixed" as const,
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "2rem",
    maxWidth: "400px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.2)",
  },
  modalTitle: { fontSize: "1.3rem", marginBottom: "1rem", color: "#1a1a1a" },
  modalText: { color: "#666", marginBottom: "1rem", lineHeight: 1.5 },
  modalActions: { display: "flex", flexDirection: "column" as const, gap: "0.75rem" },
  grid: { display: "grid", gridTemplateColumns: "1fr 2fr", gap: "2rem" },
  panel: {
    backgroundColor: "#fff",
    border: "2px solid #f7931e",
    borderRadius: "12px",
    padding: "1.5rem",
    boxShadow: "0 4px 15px rgba(0,0,0,0.1)",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1rem",
  },
  panelTitle: {
    fontSize: "1.3rem",
    margin: "0 0 1rem 0",
    color: "#ff6b35",
    fontWeight: "bold",
    flex: 1,
  },
  formGroup: { marginBottom: "1rem", display: "flex", flexDirection: "column" as const },
  inlineInput: { display: "flex", gap: "0.5rem" },
  input: {
    padding: "0.75rem",
    border: "2px solid #f7931e",
    borderRadius: "6px",
    fontSize: "0.95rem",
  },
  buttonPrimary: {
    backgroundColor: "#ff6b35",
    color: "#fff",
    border: "2px solid #ff6b35",
    padding: "0.75rem 1rem",
    borderRadius: "8px",
    cursor: "pointer",
    width: "100%",
    fontWeight: "bold",
    fontSize: "1rem",
    boxShadow: "0 4px 15px rgba(255, 107, 53, 0.4)",
  },
  buttonSecondary: {
    backgroundColor: "#fff",
    color: "#ff6b35",
    border: "2px solid #ff6b35",
    padding: "0.75rem 1rem",
    borderRadius: "8px",
    cursor: "pointer",
    width: "100%",
    fontWeight: "600",
    fontSize: "0.95rem",
  },
  buttonImport: {
    backgroundColor: "#4caf50",
    color: "#fff",
    border: "2px solid #4caf50",
    padding: "0.75rem 1rem",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "1rem",
    boxShadow: "0 4px 15px rgba(76, 175, 80, 0.4)",
  },
  buttonSkip: {
    backgroundColor: "transparent",
    color: "#666",
    border: "2px solid #ddd",
    padding: "0.75rem 1rem",
    borderRadius: "6px",
    cursor: "pointer",
  },
  buttonCancel: {
    backgroundColor: "transparent",
    color: "#666",
    border: "2px solid #ddd",
    padding: "0.75rem 1rem",
    borderRadius: "6px",
    cursor: "pointer",
    width: "100%",
  },
  buttonDelete: {
    backgroundColor: "transparent",
    color: "#d32f2f",
    border: "2px solid #d32f2f",
    padding: "0.75rem 1rem",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  buttonDeleteSmall: {
    backgroundColor: "transparent",
    border: "none",
    fontSize: "1.2rem",
    cursor: "pointer",
    padding: "0.25rem",
  },
  buttonEditSmall: {
    backgroundColor: "transparent",
    border: "none",
    fontSize: "1.2rem",
    cursor: "pointer",
    padding: "0.25rem",
  },
  buttonDeleteInChip: {
    backgroundColor: "transparent",
    color: "#fff",
    border: "none",
    fontSize: "0.9rem",
    cursor: "pointer",
    padding: "0",
    opacity: 0.8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
  },
  buttonAddInline: {
    backgroundColor: "#ff6b35",
    color: "#fff",
    border: "2px solid #ff6b35",
    borderRadius: "6px",
    padding: "0 1rem",
    fontSize: "1.4rem",
    cursor: "pointer",
    fontWeight: "bold",
    lineHeight: 1,
  },
  buttonExecute: {
    backgroundColor: "#4caf50",
    color: "#fff",
    border: "2px solid #4caf50",
    padding: "0.75rem 1rem",
    borderRadius: "8px",
    cursor: "pointer",
    width: "100%",
    marginTop: "1rem",
    fontSize: "1rem",
    fontWeight: "bold",
    boxShadow: "0 4px 15px rgba(76, 175, 80, 0.4)",
  },
  buttonImportGroup: {
    backgroundColor: "#f7931e",
    color: "#fff",
    border: "2px solid #f7931e",
    borderRadius: "6px",
    padding: "0 1.25rem",
    fontWeight: "bold",
    fontSize: "0.95rem",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  formActions: { display: "flex", flexDirection: "column" as const, gap: "0.75rem", marginTop: "1.5rem" },
  drawsList: { display: "flex", flexDirection: "column" as const, gap: "0.5rem" },
  drawItem: {
    backgroundColor: "#f9f9f9",
    border: "2px solid #ddd",
    padding: "0.75rem",
    borderRadius: "6px",
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.3s ease",
  },
  drawItemActive: {
    backgroundColor: "#fff5e1",
    borderColor: "#f7931e",
    boxShadow: "0 4px 12px rgba(247, 147, 30, 0.2)",
  },
  drawItemTitle: { fontWeight: "bold", fontSize: "0.95rem" },
  drawItemMeta: { fontSize: "0.85rem", color: "#666" },
  sectionTitle: { fontSize: "1rem", marginTop: "1.5rem", marginBottom: "0.75rem" },
  groupImportRow: { display: "flex", gap: "0.5rem", marginBottom: "0.75rem" },
  select: {
    flex: 1,
    padding: "0.75rem",
    border: "2px solid #f7931e",
    borderRadius: "6px",
    fontSize: "0.95rem",
    backgroundColor: "#fff",
    cursor: "pointer",
  },
  info: { backgroundColor: "#f9f9f9", padding: "1rem", borderRadius: "4px", marginBottom: "1rem" },
  participantsList: { display: "flex", flexWrap: "wrap" as const, gap: "0.5rem", marginTop: "0.5rem" },
  participantItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.5rem",
    backgroundColor: "#ff6b35",
    color: "#fff",
    padding: "0.4rem 0.8rem",
    borderRadius: "20px",
    fontSize: "0.9rem",
  },
  participantName: { fontWeight: "600", fontSize: "0.9rem" },
  participantCount: { fontSize: "0.85rem", color: "#666", margin: "0 0 0.5rem 0" },
  winnersList: { display: "flex", flexDirection: "column" as const, gap: "0.5rem" },
  winnerItem: {
    display: "flex",
    gap: "0.75rem",
    alignItems: "center",
    background: "linear-gradient(135deg, #fff5e1 0%, #ffe8cc 100%)",
    padding: "0.6rem 0.8rem",
    borderRadius: "8px",
    border: "2px solid #f7931e",
    boxShadow: "0 2px 8px rgba(247, 147, 30, 0.15)",
  },
  winnerRank: { fontSize: "1.3rem", fontWeight: "bold", color: "#ff6b35", minWidth: "2rem", textAlign: "center" },
  winnerName: { fontWeight: "bold", fontSize: "0.9rem" },
  wheelSection: {
    marginTop: "2rem",
    padding: "1rem",
    backgroundColor: "#fff5e1",
    borderRadius: "12px",
    border: "2px solid #f7931e",
    textAlign: "center" as const,
  },
  wheelTitle: {
    fontSize: "1.3rem",
    color: "#ff6b35",
    marginBottom: "1rem",
    animation: "bounce 1.5s ease-in-out infinite",
  },
  groupsList: { display: "flex", flexDirection: "column" as const },
  groupCard: {
    padding: "1.25rem 0.75rem",
    borderBottom: "1px solid #eee",
    transition: "background 0.2s ease",
  },
  groupCardLast: { borderBottom: "none" },
  groupCardActive: {
    backgroundColor: "#fff5e1",
    borderBottom: "1px solid #f7931e",
    borderRadius: "8px",
    padding: "1.25rem",
  },
  groupCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "0.75rem",
  },
  groupCardName: { fontWeight: "bold", fontSize: "1rem", color: "#1a1a1a", display: "block", marginBottom: "0.2rem" },
  groupCardCount: { fontSize: "0.8rem", color: "#999" },
  groupCardActions: { display: "flex", gap: "0.25rem" },
  emptyLabel: { fontSize: "0.85rem", color: "#aaa", fontStyle: "italic" },
};

export default styles;
